version: "3"
services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/symfony.conf:/etc/nginx/conf.d/symfony.conf
      - ./symfony:/app/symfony
      - ../letsencrypt:/certs

  app:
    build: app
    ports:
      - 800:800
    volumes:
      - ./app/entrypoint-nginx.sh:/entrypoint.sh
      - ./symfony:/app/symfony
      - ./app/www.conf:/etc/php/8.2/fpm/pool.d/www.conf
      - ./prod/.env:/app/symfony/.env


